import turtle
width, height = 600, 400   
window = turtle.Screen()    
turtle = turtle.turtle()    
turtle.hideturtle()    
turtle.speed(1) 
turtle.penup()    
turtle.goto(-width/2, height/2)    
turtle.pendown()    
turtle.begin_fill()   
turtle.fillcolor('red')    
turtle.fd(width)    
turtle.right(90)    
turtle.fd(height)    
turtle.right(90)    
turtle.fd(width)    
turtle.right(90)    
turtle.fd(height)    
turtle.right(90)        
turtle.end_fill()

turtle.goto(-width*11/30,height/10)
turtle.pendown()
turtle.begin_fill()
for i in range(5):
    turtle.left(144)
    turtle.back(240)
turtle.fillcolor('yellow')
turtle.end_fill()    
turtle.penup()

turtle.goto(width/10,height*3/10)
turtle.pendown()
turtle.begin_fill()
for i in range (5):
    turtle.left(144)
    turtle.back(120)
turtle.fillcolor('yellow')
turtle.end_fill()     
turtle.penup()

turtle.goto(width*11/30,height/10)
turtle.pendown()
turtle.begin_fill()
for i in range(5):
    turtle.left(144)
    turtle.back(120)  
turtle.fillcolor('yellow')
turtle.end_fill() 
turtle.penup()

turtle.goto(width*11/30,-height/10)
turtle.pendown()
turtle.begin_fill()
for i in range(5):
    turtle.left(144)
    turtle.back(120)  
turtle.fillcolor('yellow')
turtle.end_fill() 
turtle.penup()

turtle.goto(width/10,-height*4/10)
turtle.pendown()
turtle.begin_fill()
for i in range (5):
    turtle.left(144)
    turtle.back(120) 
turtle.fillcolor('yellow')
turtle.end_fill()
turtle.penup()
